sudo: required
services:
  - docker

before_install:
  - docker build -t higginator/docker-react-tut -f Dockerfile.dev .

script:
  - docker run -e CI=true higginator/docker-react-tut npm run test

deploy:
  provider: 'elasticbeanstalk'
  region: 'us-east-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-284562680108'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
